-- City Pulse MVP schema
-- Run this in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  100000,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'business-media',
  'business-media',
  true,
  300000,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post-images',
  'post-images',
  true,
  300000,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  role text not null default 'user',
  category text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists name text,
  add column if not exists role text not null default 'user',
  add column if not exists category text,
  add column if not exists avatar_url text,
  add column if not exists bio text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.businesses (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  category text not null default 'localuri',
  subtitle text,
  location_name text,
  latitude double precision,
  longitude double precision,
  image_url text,
  logo_url text,
  phone text,
  instagram text,
  website text,
  schedule text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.businesses
  add column if not exists name text,
  add column if not exists category text not null default 'localuri',
  add column if not exists subtitle text,
  add column if not exists location_name text,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists image_url text,
  add column if not exists logo_url text,
  add column if not exists phone text,
  add column if not exists instagram text,
  add column if not exists website text,
  add column if not exists schedule text,
  add column if not exists description text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  business_id uuid references public.businesses(id) on delete set null,
  category text not null default 'anunturi',
  business_name text not null default 'Business local',
  avatar text,
  tag text,
  text text not null,
  image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.posts
  add column if not exists business_id uuid references public.businesses(id) on delete set null,
  add column if not exists category text not null default 'anunturi',
  add column if not exists business_name text not null default 'Business local',
  add column if not exists avatar text,
  add column if not exists tag text,
  add column if not exists text text not null default '',
  add column if not exists image text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  business_name text not null default 'Business local',
  type text not null default 'Meetups',
  title text not null,
  description text,
  event_date date not null,
  event_time text,
  location_name text,
  address text,
  price text,
  poster_url text,
  lineup text[] not null default '{}',
  gallery text[] not null default '{}',
  attendees integer not null default 0,
  interested integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.events
  add column if not exists business_id uuid references public.businesses(id) on delete cascade,
  add column if not exists business_name text not null default 'Business local',
  add column if not exists type text not null default 'Meetups',
  add column if not exists title text not null default 'Eveniment local',
  add column if not exists description text,
  add column if not exists event_date date not null default current_date,
  add column if not exists event_time text,
  add column if not exists location_name text,
  add column if not exists address text,
  add column if not exists price text,
  add column if not exists poster_url text,
  add column if not exists lineup text[] not null default '{}',
  add column if not exists gallery text[] not null default '{}',
  add column if not exists attendees integer not null default 0,
  add column if not exists interested integer not null default 0,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.event_participants (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);

alter table public.event_participants
  add column if not exists event_id uuid references public.events(id) on delete cascade,
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  target_role text not null default 'all',
  actor_id uuid references auth.users(id) on delete set null,
  type text not null default 'system',
  title text not null,
  body text,
  href text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.notifications
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists target_role text not null default 'all',
  add column if not exists actor_id uuid references auth.users(id) on delete set null,
  add column if not exists type text not null default 'system',
  add column if not exists title text not null default 'Notificare',
  add column if not exists body text,
  add column if not exists href text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.notification_reads (
  notification_id uuid not null references public.notifications(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);

alter table public.notification_reads
  add column if not exists notification_id uuid references public.notifications(id) on delete cascade,
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists read_at timestamptz not null default now();

update public.posts posts
set business_id = businesses.id
from public.businesses businesses
where posts.business_id is null
  and lower(posts.business_name) = lower(businesses.name);

alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
alter table public.posts enable row level security;
alter table public.events enable row level security;
alter table public.event_participants enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;

drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public"
on public.profiles for select
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "businesses_select_public" on public.businesses;
create policy "businesses_select_public"
on public.businesses for select
using (true);

drop policy if exists "businesses_insert_own" on public.businesses;
create policy "businesses_insert_own"
on public.businesses for insert
with check (auth.uid() = id);

drop policy if exists "businesses_update_own" on public.businesses;
create policy "businesses_update_own"
on public.businesses for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "posts_select_public" on public.posts;
create policy "posts_select_public"
on public.posts for select
using (true);

drop policy if exists "posts_insert_own_business" on public.posts;
create policy "posts_insert_own_business"
on public.posts for insert
with check (auth.uid() = business_id);

drop policy if exists "posts_update_own_business" on public.posts;
create policy "posts_update_own_business"
on public.posts for update
using (auth.uid() = business_id)
with check (auth.uid() = business_id);

drop policy if exists "posts_delete_own_business" on public.posts;
create policy "posts_delete_own_business"
on public.posts for delete
using (auth.uid() = business_id);

drop policy if exists "events_select_public" on public.events;
create policy "events_select_public"
on public.events for select
using (true);

drop policy if exists "events_insert_own_business" on public.events;
create policy "events_insert_own_business"
on public.events for insert
with check (auth.uid() = business_id);

drop policy if exists "events_update_own_business" on public.events;
create policy "events_update_own_business"
on public.events for update
using (auth.uid() = business_id)
with check (auth.uid() = business_id);

drop policy if exists "events_delete_own_business" on public.events;
create policy "events_delete_own_business"
on public.events for delete
using (auth.uid() = business_id);

drop policy if exists "event_participants_select_public" on public.event_participants;
create policy "event_participants_select_public"
on public.event_participants for select
using (true);

drop policy if exists "event_participants_insert_own" on public.event_participants;
create policy "event_participants_insert_own"
on public.event_participants for insert
with check (auth.uid() = user_id);

drop policy if exists "event_participants_delete_own" on public.event_participants;
create policy "event_participants_delete_own"
on public.event_participants for delete
using (auth.uid() = user_id);

drop policy if exists "notifications_select_relevant" on public.notifications;
create policy "notifications_select_relevant"
on public.notifications for select
using (
  auth.uid() is not null
  and (user_id is null or user_id = auth.uid())
  and (
    target_role = 'all'
    or target_role = coalesce(
      (select role from public.profiles where id = auth.uid()),
      'user'
    )
  )
);

drop policy if exists "notifications_insert_authenticated" on public.notifications;
create policy "notifications_insert_authenticated"
on public.notifications for insert
with check (auth.uid() is not null);

drop policy if exists "notification_reads_select_own" on public.notification_reads;
create policy "notification_reads_select_own"
on public.notification_reads for select
using (auth.uid() = user_id);

drop policy if exists "notification_reads_insert_own" on public.notification_reads;
create policy "notification_reads_insert_own"
on public.notification_reads for insert
with check (auth.uid() = user_id);

drop policy if exists "notification_reads_update_own" on public.notification_reads;
create policy "notification_reads_update_own"
on public.notification_reads for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "avatars_select_public" on storage.objects;
create policy "avatars_select_public"
on storage.objects for select
using (bucket_id = 'avatars');

drop policy if exists "avatars_insert_own" on storage.objects;
create policy "avatars_insert_own"
on storage.objects for insert
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "avatars_update_own" on storage.objects;
create policy "avatars_update_own"
on storage.objects for update
using (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "avatars_delete_own" on storage.objects;
create policy "avatars_delete_own"
on storage.objects for delete
using (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "business_media_select_public" on storage.objects;
create policy "business_media_select_public"
on storage.objects for select
using (bucket_id = 'business-media');

drop policy if exists "business_media_insert_own" on storage.objects;
create policy "business_media_insert_own"
on storage.objects for insert
with check (
  bucket_id = 'business-media'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "business_media_update_own" on storage.objects;
create policy "business_media_update_own"
on storage.objects for update
using (
  bucket_id = 'business-media'
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'business-media'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "business_media_delete_own" on storage.objects;
create policy "business_media_delete_own"
on storage.objects for delete
using (
  bucket_id = 'business-media'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "post_images_select_public" on storage.objects;
create policy "post_images_select_public"
on storage.objects for select
using (bucket_id = 'post-images');

drop policy if exists "post_images_insert_authenticated" on storage.objects;
create policy "post_images_insert_authenticated"
on storage.objects for insert
with check (
  bucket_id = 'post-images'
  and auth.uid() is not null
);

drop policy if exists "post_images_update_authenticated" on storage.objects;
create policy "post_images_update_authenticated"
on storage.objects for update
using (
  bucket_id = 'post-images'
  and auth.uid() is not null
)
with check (
  bucket_id = 'post-images'
  and auth.uid() is not null
);

drop policy if exists "post_images_delete_authenticated" on storage.objects;
create policy "post_images_delete_authenticated"
on storage.objects for delete
using (
  bucket_id = 'post-images'
  and auth.uid() is not null
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists businesses_set_updated_at on public.businesses;
create trigger businesses_set_updated_at
before update on public.businesses
for each row execute function public.set_updated_at();

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at
before update on public.events
for each row execute function public.set_updated_at();
